apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-visualization
spec:
  replicas: 3
  selector:
    matchLabels:
      app: robot-visualization
  template:
    metadata:
      labels:
        app: robot-visualization
    spec:
      containers:
      - name: fiware-robot-visualization
        image: roboticbase/fiware-robot-visualization:0.3.0
        imagePullPolicy: Always
        env:
        - name: LISTEN_PORT
          value: "8888"
        - name: PREFIX
          value: "/visualizer"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: BEARER_AUTH
          value: "${BEARER_AUTH}"
        - name: API_VERSION
          value: "v2"
        - name: FETCH_LIMIT
          value: "128"
        - name: COMET_ENDPOINT
          value: "http://comet:8666"
        - name: FIWARE_SERVICE
          value: "${FIWARE_SERVICE}"
        - name: FIWARE_SERVICEPATH
          value: "${ROBOT_SERVICEPATH}"
        - name: ENTITY_TYPE
          value: "${ROBOT_TYPE}"
        - name: ENTITY_ID
          value: "${ROBOT_ID}"
        ports:
          - name: robot-vis
            containerPort: 8888
